### PR TITLE
Build : Add TabBar as a key window  🪟

### PR DESCRIPTION
**Pull request by a7maad-ayman**
- create a method to retrieve  a navigation controller 
- create a method to retrieve a tabBar controller 
- passing the method of the tabBar as a key window

### CODE REVIEW

**Review by ahmdyasser — COMMENTED** [review]
- Add all generated files to `.gitignore` file
- Remove SwiftLint disabling comments from your Swift files and add the rules you want to disable to `.swiftlint.yml` file

**Comment by ahmdyasser** [comment]
remove stencil files
image

**Comment by a7maad-ayman** [comment]
> 



> remove stencil files image

stencil file is a template file for swiftGent auto generated images not an auto generated file itself

**Comment by ahmdyasser** [comment]
@a7maad-ayman any file or folder that goes under Generated folder should be added to `.gitignore`

**Pull request merged**
